export type GrammarLesson = {
  sentence: string
  target: string
  choices: readonly string[]
  focus: string
  thai: string
  why: string
  whyThai: string
  practice?: { id: string; readingId: string }
}

// Individually authored grammar contrasts. A story's original wording alone
// is never the reason an alternative is marked wrong. Keep the noun/verb
// content intact and give the intended meaning before asking for a choice.
export const grammarLessons: readonly GrammarLesson[] = [
  { sentence: 'Also, your child needs the right supplies.', target: 'the', choices: ['the', 'a', 'an'], focus: 'The before plural nouns', thai: 'นอกจากนี้ ลูกของคุณต้องมีอุปกรณ์ที่เหมาะสม', why: 'Supplies is plural. The can introduce right supplies; a and an only introduce singular countable nouns.', whyThai: 'supplies เป็นคำนามพหูพจน์ ใช้ the นำหน้า right supplies ได้ ส่วน a และ an ใช้กับคำนามนับได้เอกพจน์เท่านั้น' },
  { sentence: 'There are many houses in the suburbs.', target: 'the', choices: ['the', 'a', 'an'], focus: 'The before plural place nouns', thai: 'มีบ้านหลายหลังอยู่ในเขตชานเมือง', why: 'Suburbs is plural. The works before this plural noun; a suburbs and an suburbs do not.', whyThai: 'suburbs เป็นพหูพจน์ จึงใช้ the ได้ แต่ใช้ a suburbs หรือ an suburbs ไม่ได้' },
  { sentence: 'The rocks in Cappadocia are kind of soft.', target: 'The', choices: ['The', 'This', 'That'], focus: 'The with a plural subject', thai: 'หินในคัปปาโดเกียค่อนข้างนิ่ม', why: 'Rocks is plural. The can introduce plural rocks, while this and that require a singular noun here.', whyThai: 'rocks เป็นพหูพจน์ ใช้ the นำหน้าได้ ส่วน this และ that ต้องตามด้วยคำนามเอกพจน์ในตำแหน่งนี้' },
  { sentence: 'Some big cities build train tracks above the city streets.', target: 'the', choices: ['the', 'this', 'that'], focus: 'The before a plural noun phrase', thai: 'เมืองใหญ่บางเมืองสร้างรางรถไฟไว้เหนือถนนในเมือง', why: 'The main noun is streets, which is plural; city describes the streets. The fits, but this city streets and that city streets do not.', whyThai: 'คำนามหลักคือ streets ซึ่งเป็นพหูพจน์ ส่วน city ขยาย streets จึงใช้ the ได้ แต่ใช้ this city streets หรือ that city streets ไม่ได้' },
  { sentence: 'Sometimes birders hike in the woods or up and down hills.', target: 'the', choices: ['the', 'they', 'them'], focus: 'The after a preposition and before a noun', thai: 'บางครั้งนักดูนกเดินป่าหรือเดินขึ้นลงเนินเขา', why: 'The introduces the noun woods after in. They and them are pronouns, not determiners that can introduce woods.', whyThai: 'the ใช้นำหน้าคำนาม woods หลัง in ได้ ส่วน they และ them เป็นสรรพนาม ไม่ใช่คำนำหน้านาม woods' },
  { sentence: 'The dish is traditionally served in a cone of newspaper.', target: 'The', choices: ['The', 'These', 'Those'], focus: 'The with a singular subject', thai: 'ตามธรรมเนียม อาหารจานนี้เสิร์ฟในกระดาษหนังสือพิมพ์ที่ม้วนเป็นกรวย', why: 'Dish is singular. The fits a singular noun; these and those require a plural noun here.', whyThai: 'dish เป็นเอกพจน์ ใช้ the นำหน้าได้ ส่วน these และ those ต้องตามด้วยคำนามพหูพจน์ในตำแหน่งนี้' },
  { sentence: 'They sweep across the dark sky.', target: 'the', choices: ['the', 'these', 'those'], focus: 'The before an adjective and singular noun', thai: 'ดาวตกเหล่านั้นพุ่งผ่านท้องฟ้าที่มืดมิด', why: 'Sky is singular, and dark describes it. The can introduce dark sky; these and those cannot introduce the singular noun sky.', whyThai: 'sky เป็นเอกพจน์ และ dark ขยาย sky จึงใช้ the นำหน้า dark sky ได้ แต่ใช้ these หรือ those กับ sky ที่เป็นเอกพจน์ไม่ได้' },
  { sentence: 'He held the door open for me.', target: 'the', choices: ['the', 'they', 'them'], focus: 'The before the object noun', thai: 'เขาจับประตูเปิดไว้ให้ฉัน', why: 'The introduces door, the object of held. They and them cannot introduce the noun door in this position.', whyThai: 'the นำหน้า door ซึ่งเป็นกรรมของ held ส่วน they และ them ใช้นำหน้าคำนาม door ในตำแหน่งนี้ไม่ได้' },
  { sentence: 'The average temperature is about fifteen degrees Celsius.', target: 'The', choices: ['The', 'They', 'Them'], focus: 'The before an adjective and noun', thai: 'อุณหภูมิเฉลี่ยอยู่ที่ประมาณสิบห้าองศาเซลเซียส', why: 'The introduces the noun phrase average temperature. They and them are pronouns and cannot introduce that noun phrase.', whyThai: 'the นำหน้ากลุ่มคำนาม average temperature ได้ ส่วน they และ them เป็นสรรพนามและใช้นำหน้ากลุ่มคำนามนี้ไม่ได้' },
  { sentence: 'My grandfather is a pilot.', target: 'is', choices: ['is', 'are', 'am'], focus: 'Subject–verb agreement', thai: 'ปู่หรือตาของฉันเป็นนักบิน', why: 'My grandfather is one person. Use is with a singular third-person subject.', whyThai: 'ปู่หรือตาเป็นคนเดียว จึงใช้ is ไม่ใช่ are หรือ am' },
  { sentence: 'My grandmother is a chef.', target: 'a', choices: ['a', 'an'], focus: 'Articles: a / an', thai: 'ย่าหรือยายของฉันเป็นเชฟ', why: 'Chef begins with a consonant sound, so use a, not an.', whyThai: 'chef เริ่มด้วยเสียงพยัญชนะ จึงใช้ a ไม่ใช่ an' },
  { sentence: 'There are eight people in my family.', target: 'are', choices: ['are', 'is', 'am'], focus: 'There is / there are', thai: 'ในครอบครัวของฉันมีแปดคน', why: 'Eight people is plural. Use there are.', whyThai: 'eight people เป็นพหูพจน์ จึงใช้ there are' },
  { sentence: 'We are a big family!', target: 'We', choices: ['We', 'Us', 'Our'], focus: 'Subject pronouns', thai: 'พวกเราเป็นครอบครัวใหญ่!', why: 'The subject before are is we. Us is an object; our goes before a noun.', whyThai: 'คำที่เป็นประธานหน้า are ต้องเป็น we ส่วน us เป็นกรรม และ our ใช้หน้าคำนามเพื่อบอกความเป็นเจ้าของ' },
  { sentence: 'My grandmother and grandfather also live with us.', target: 'us', choices: ['us', 'we', 'our'], focus: 'Object pronouns after prepositions', thai: 'ย่าหรือยายและปู่หรือตาของฉันก็อยู่กับพวกเราด้วย', why: 'After with, use the object form us, not the subject form we or possessive our.', whyThai: 'หลัง with ใช้สรรพนามรูปกรรม us ไม่ใช่ we หรือ our' },
  { sentence: 'Do you have a big family?', target: 'Do', choices: ['Do', 'Does'], focus: 'Questions: do / does', thai: 'คุณมีครอบครัวใหญ่ไหม?', why: 'Use do with you. Does goes with he, she, or it.', whyThai: 'ประธาน you ใช้ do ส่วน he, she และ it ใช้ does' },
  { sentence: 'Thanks a lot for your last letter.', target: 'for', choices: ['for', 'of', 'on'], focus: 'Prepositions: thanks for', thai: 'ขอบคุณมากสำหรับจดหมายฉบับล่าสุดของคุณ', why: 'Use thanks for to name the thing you are grateful for.', whyThai: 'ใช้ thanks for เพื่อบอกว่าขอบคุณสำหรับสิ่งใด' },
  { sentence: 'Your child needs to be happy at school.', target: 'Your', choices: ['Your', 'You', 'Yours'], focus: 'Possessive determiners', thai: 'ลูกของคุณต้องมีความสุขที่โรงเรียน', why: 'Your comes before child to show whose child. You is a subject; yours stands without the noun.', whyThai: 'your อยู่หน้าคำนาม child เพื่อบอกว่าเป็นลูกของใคร ส่วน you เป็นประธาน และ yours ใช้แทนคำนาม' },
  { sentence: 'Your child needs to be happy at school.', target: 'to', choices: ['to', 'of', 'at'], focus: 'Infinitive marker: needs to', thai: 'ลูกของคุณต้องมีความสุขที่โรงเรียน', why: 'Use needs to followed by the base verb be.', whyThai: 'ใช้ needs to ตามด้วยกริยารูปพื้นฐาน be' },
  { sentence: 'Your child will write a lot.', target: 'will', choices: ['will', 'is', 'are'], focus: 'Auxiliaries before a base verb', thai: 'ลูกของคุณจะเขียนเยอะ', why: 'Will expresses จะ and is followed by the base verb write. Is and are cannot directly precede write here.', whyThai: 'will หมายถึง จะ และตามด้วย write ได้ ส่วน is และ are ตามด้วย write ตรง ๆ แบบนี้ไม่ได้' },
  { sentence: 'What does your child do for fun?', target: 'does', choices: ['does', 'do'], focus: 'Questions: do / does', thai: 'ลูกของคุณทำอะไรเพื่อความสนุก?', why: 'Your child is singular, so this present-simple question uses does.', whyThai: 'your child เป็นเอกพจน์ คำถามในปัจจุบันจึงใช้ does' },
  { sentence: 'Please get these things before the first day of school.', target: 'these', choices: ['these', 'this'], focus: 'Demonstratives: this / these', thai: 'กรุณาหาของเหล่านี้ให้พร้อมก่อนวันเปิดเรียนวันแรก', why: 'Things is plural, so use these rather than this.', whyThai: 'things เป็นพหูพจน์ จึงใช้ these ไม่ใช่ this' },
  { sentence: 'Please get these things before the first day of school.', target: 'before', choices: ['before', 'beforehand', 'ago'], focus: 'Before introducing a time', thai: 'กรุณาหาของเหล่านี้ให้พร้อมก่อนวันเปิดเรียนวันแรก', why: 'Before can introduce the first day of school. Beforehand stands alone; ago follows a duration and cannot introduce the first day.', whyThai: 'before ใช้นำหน้า the first day of school ได้ ส่วน beforehand ใช้เดี่ยว ๆ และ ago อยู่หลังระยะเวลา' },
  { sentence: 'This house is in Serbia.', target: 'This', choices: ['This', 'These'], focus: 'Demonstratives: this / these', thai: 'บ้านหลังนี้อยู่ในประเทศเซอร์เบีย', why: 'House is singular, so use this. These requires a plural noun.', whyThai: 'house เป็นบ้านหลังเดียว จึงใช้ this ส่วน these ใช้กับคำนามพหูพจน์' },
  { sentence: 'This house is in Serbia.', target: 'in', choices: ['in', 'on', 'of'], focus: 'Prepositions: in a country', thai: 'บ้านหลังนี้อยู่ในประเทศเซอร์เบีย', why: 'Use in to locate a house within a country.', whyThai: 'ใช้ in เพื่อบอกว่าบ้านอยู่ในประเทศใด' },
  { sentence: 'People made them inside large rocks.', target: 'them', choices: ['them', 'they', 'their'], focus: 'Object pronouns', thai: 'ผู้คนสร้างบ้านเหล่านั้นไว้ภายในหินก้อนใหญ่', why: 'The cave houses receive the action made, so use the object pronoun them. They is a subject; their needs a noun.', whyThai: 'บ้านเหล่านั้นเป็นสิ่งที่ถูกสร้าง จึงใช้สรรพนามรูปกรรม them ส่วน they เป็นประธาน และ their ต้องตามด้วยคำนาม' },
  { sentence: 'They are near the beautiful Diamond Beach.', target: 'They', choices: ['They', 'Them', 'Their'], focus: 'Subject pronouns', thai: 'บ้านต้นไม้เหล่านั้นอยู่ใกล้หาดไดมอนด์ที่สวยงาม', why: 'The subject of are must be they, not them or their.', whyThai: 'ประธานของ are ต้องเป็น they ไม่ใช่ them หรือ their' },
  { sentence: 'The rocks in Cappadocia are kind of soft.', target: 'are', choices: ['are', 'is', 'am'], focus: 'Subject–verb agreement', thai: 'หินในคัปปาโดเกียค่อนข้างนิ่ม', why: 'The subject is the rocks, which is plural. Use are even though Cappadocia is nearby.', whyThai: 'ประธานคือ the rocks ซึ่งเป็นพหูพจน์ จึงใช้ are แม้จะมีชื่อ Cappadocia อยู่ใกล้กริยา' },
  { sentence: 'One of these cities is Chicago.', target: 'these', choices: ['these', 'this'], focus: 'Demonstratives with plural nouns', thai: 'หนึ่งในเมืองเหล่านี้คือชิคาโก', why: 'These describes the plural noun cities. One does not change the form needed before cities.', whyThai: 'these ขยาย cities ซึ่งเป็นพหูพจน์ คำว่า one ไม่ได้ทำให้ cities กลายเป็นเอกพจน์' },
  { sentence: 'One of these cities is Chicago.', target: 'is', choices: ['is', 'are', 'am'], focus: 'Agreement with one of', thai: 'หนึ่งในเมืองเหล่านี้คือชิคาโก', why: 'The subject is one of these cities: one city. Use is.', whyThai: 'ประธานคือหนึ่งเมืองจากหลายเมือง จึงใช้ is' },
  { sentence: 'Above them, trains are moving from station to station with no traffic jams.', target: 'them', choices: ['them', 'they', 'their'], focus: 'Object pronouns after prepositions', thai: 'เหนือรถยนต์และรถโดยสารเหล่านั้น รถไฟกำลังเคลื่อนจากสถานีหนึ่งไปอีกสถานีหนึ่งโดยไม่มีรถติด', why: 'Above is a preposition. The pronoun after it takes the object form them.', whyThai: 'above เป็นคำบุพบท สรรพนามที่ตามหลังจึงใช้รูปกรรม them' },
  { sentence: 'Above them, trains are moving from station to station with no traffic jams.', target: 'to', choices: ['to', 'of', 'at'], focus: 'Prepositions: from … to …', thai: 'เหนือรถยนต์และรถโดยสารเหล่านั้น รถไฟกำลังเคลื่อนจากสถานีหนึ่งไปอีกสถานีหนึ่งโดยไม่มีรถติด', why: 'From station to station expresses movement from one station to another.', whyThai: 'from station to station แสดงการเคลื่อนจากสถานีหนึ่งไปยังอีกสถานีหนึ่ง' },
  { sentence: 'Riding the train is easy.', target: 'the', choices: ['the', 'they', 'them'], focus: 'Articles before nouns', thai: 'การโดยสารรถไฟนั้นเป็นเรื่องง่าย', why: 'The is an article that can introduce train. They and them are pronouns and cannot introduce train here.', whyThai: 'the เป็นคำนำหน้านาม train ได้ ส่วน they และ them เป็นสรรพนาม ใช้นำหน้า train แบบนี้ไม่ได้' },
  { sentence: 'A train is passing over your head!', target: 'your', choices: ['your', 'you', 'yours'], focus: 'Possessive determiners', thai: 'รถไฟขบวนหนึ่งกำลังแล่นผ่านเหนือศีรษะของคุณ!', why: 'Use your before the noun head to show whose head.', whyThai: 'ใช้ your หน้าคำนาม head เพื่อบอกว่าเป็นศีรษะของคุณ' },
  { sentence: 'At night and on weekends, they do not come as often.', target: 'At', choices: ['At', 'On'], focus: 'Time prepositions: at night', thai: 'ตอนกลางคืนและในวันหยุดสุดสัปดาห์ รถไฟไม่ได้มาบ่อยเท่านั้น', why: 'The usual expression for night in general is at night, not on night.', whyThai: 'สำนวนที่ใช้กับกลางคืนโดยทั่วไปคือ at night ไม่ใช่ on night' },
  { sentence: 'The tracks are supported by massive steel columns.', target: 'by', choices: ['by', 'because', 'they'], focus: 'Prepositions in the passive', thai: 'รางรถไฟมีเสาเหล็กขนาดใหญ่รองรับอยู่', why: 'In this passive sentence, by introduces what supports the tracks.', whyThai: 'ในประโยคนี้ by นำหน้าสิ่งที่รองรับรางรถไฟ คือเสาเหล็ก' },
  { sentence: 'I save extra food for them.', target: 'them', choices: ['them', 'they', 'their'], focus: 'Object pronouns after prepositions', thai: 'ฉันเก็บอาหารส่วนที่เหลือไว้ให้แมวเหล่านั้น', why: 'After for, use the object pronoun them to refer to the cats.', whyThai: 'หลัง for ใช้สรรพนามรูปกรรม them เพื่อแทนแมวเหล่านั้น' },
  { sentence: 'I feed cats near my home.', target: 'my', choices: ['my', 'me', 'I'], focus: 'Possessive determiners', thai: 'ฉันให้อาหารแมวใกล้บ้านของฉัน', why: 'My goes before home to show possession. Me and I do not.', whyThai: 'my อยู่หน้า home เพื่อบอกว่าเป็นบ้านของฉัน ส่วน me และ I ใช้แบบนี้ไม่ได้' },
  { sentence: 'These are not pet cats.', target: 'These', choices: ['These', 'This'], focus: 'Demonstratives and agreement', thai: 'แมวเหล่านี้ไม่ใช่แมวเลี้ยง', why: 'The plural cats and are require these, not this.', whyThai: 'cats เป็นพหูพจน์และใช้ are จึงต้องใช้ these ไม่ใช่ this' },
  { sentence: 'I can play basketball with my friends.', target: 'with', choices: ['with', 'of', 'to'], focus: 'Prepositions: with someone', thai: 'ฉันสามารถเล่นบาสเกตบอลกับเพื่อน ๆ ของฉันได้', why: 'With means together with someone; the Thai says กับเพื่อน ๆ.', whyThai: 'with หมายถึง กับ ในที่นี้คือเล่นกับเพื่อน ๆ' },
  { sentence: 'They sweep across the dark sky.', target: 'They', choices: ['They', 'Them', 'Their'], focus: 'Subject pronouns', thai: 'ดาวตกเหล่านั้นพุ่งผ่านท้องฟ้าที่มืดมิด', why: 'The shooting stars do the action sweep, so use the subject pronoun they.', whyThai: 'ดาวตกเป็นผู้ทำกริยา sweep จึงใช้สรรพนามรูปประธาน they' },
  { sentence: 'Then look at its color patterns.', target: 'its', choices: ['its', "it's"], focus: 'Possessive its / it is', thai: 'จากนั้นให้ดูรูปแบบสีของนกตัวนั้น', why: 'Its means belonging to it. It’s means it is or it has and does not fit before color patterns.', whyThai: 'its หมายถึง ของมัน ส่วน it’s ย่อจาก it is หรือ it has จึงใช้หน้าคำว่า color patterns แบบนี้ไม่ได้' },
  { sentence: 'They want to remember each bird.', target: 'to', choices: ['to', 'of', 'at'], focus: 'Infinitive marker: want to', thai: 'พวกเขาต้องการจดจำนกแต่ละตัว', why: 'Want is followed by to plus the base verb: want to remember.', whyThai: 'หลัง want ใช้ to ตามด้วยกริยารูปพื้นฐาน เช่น want to remember' },
  { sentence: 'You can learn bird calls by listening to audio online.', target: 'by', choices: ['by', 'of', 'to'], focus: 'Prepositions: by + -ing', thai: 'คุณสามารถเรียนรู้เสียงร้องของนกได้ด้วยการฟังเสียงทางออนไลน์', why: 'By listening explains the method: how you learn.', whyThai: 'by listening บอกวิธีการเรียนรู้ คือด้วยการฟัง' },
  { sentence: 'You can learn bird calls by listening to audio online.', target: 'to', choices: ['to', 'at', 'of'], focus: 'Prepositions: listen to', thai: 'คุณสามารถเรียนรู้เสียงร้องของนกได้ด้วยการฟังเสียงทางออนไลน์', why: 'Use listen to before the thing you hear: listening to audio.', whyThai: 'ใช้ listen to หน้าสิ่งที่ฟัง เช่น listening to audio' },
  { sentence: 'They often take a photo or a video of the bird.', target: 'of', choices: ['of', 'than', 'because'], focus: 'Prepositions: a photo of', thai: 'พวกเขามักถ่ายรูปหรือวิดีโอของนกตัวนั้น', why: 'Of links the photo or video to the bird it shows. Than requires a comparison; because needs a clause.', whyThai: 'of เชื่อมรูปหรือวิดีโอกับนกที่อยู่ในภาพ ส่วน than ต้องใช้ในการเปรียบเทียบ และ because ต้องตามด้วยประโยคย่อย' },
  { sentence: 'It is usually served with pita bread.', target: 'with', choices: ['with', 'of', 'at'], focus: 'Prepositions: accompaniment', thai: 'อาหารนี้มักเสิร์ฟพร้อมกับขนมปังพิตา', why: 'With introduces the food served alongside it.', whyThai: 'with บอกสิ่งที่เสิร์ฟมาพร้อมกัน คือขนมปังพิตา' },
  { sentence: 'This week, I went to Colorado to visit my sister.', target: 'my', choices: ['my', 'me', 'I'], focus: 'Possessive determiners', thai: 'สัปดาห์นี้ฉันไปโคโลราโดเพื่อเยี่ยมพี่สาวหรือน้องสาวของฉัน', why: 'My goes before sister to show whose sister. The noun sister is already supplied; you are choosing its grammatical determiner.', whyThai: 'my อยู่หน้า sister เพื่อบอกว่าเป็นพี่สาวหรือน้องสาวของฉัน โจทย์ให้คำนาม sister มาแล้ว' },
  { sentence: 'The man at the gate saw me running.', target: 'me', choices: ['me', 'I', 'my'], focus: 'Object pronouns', thai: 'ผู้ชายที่ประตูขึ้นเครื่องเห็นฉันกำลังวิ่ง', why: 'The man is the subject. The person he saw is the object, so use me.', whyThai: 'ผู้ชายเป็นประธาน ส่วนฉันเป็นคนที่เขาเห็น จึงใช้รูปกรรม me' },
  { sentence: 'At the airport, I hugged her.', target: 'her', choices: ['her', 'she'], focus: 'Object pronouns', thai: 'ที่สนามบิน ฉันกอดเธอ', why: 'Her is the object of hugged. She is a subject form and cannot be the object here.', whyThai: 'her เป็นกรรมของ hugged ส่วน she เป็นรูปประธาน ใช้เป็นกรรมในตำแหน่งนี้ไม่ได้' },
  { sentence: 'He held the door open for me.', target: 'me', choices: ['me', 'I', 'my'], focus: 'Object pronouns after prepositions', thai: 'เขาจับประตูเปิดไว้ให้ฉัน', why: 'The pronoun after for must be the object form me.', whyThai: 'สรรพนามหลัง for ต้องเป็นรูปกรรม me' },
  { sentence: 'My plane was ready to leave!', target: 'was', choices: ['was', 'were'], focus: 'Past be: was / were', thai: 'ตอนนั้นเครื่องบินของฉันพร้อมจะออกเดินทางแล้ว!', why: 'My plane is singular, so the past form is was, not were.', whyThai: 'my plane เป็นเอกพจน์ ในอดีตจึงใช้ was ไม่ใช่ were' },
  { sentence: 'Our island is very far from other countries.', target: 'Our', choices: ['Our', 'We', 'Us'], focus: 'Possessive determiners', thai: 'เกาะของพวกเราอยู่ห่างจากประเทศอื่น ๆ มาก', why: 'Our introduces island and tells us whose island it is.', whyThai: 'our อยู่หน้า island เพื่อบอกว่าเป็นเกาะของพวกเรา' },
  { sentence: 'Our island is very far from other countries.', target: 'from', choices: ['from', 'of', 'on'], focus: 'Prepositions: far from', thai: 'เกาะของพวกเราอยู่ห่างจากประเทศอื่น ๆ มาก', why: 'Far from expresses distance away from a place.', whyThai: 'far from หมายถึงอยู่ห่างจากสถานที่หนึ่ง' },
  { sentence: 'Summer is sunny because the sun doesn’t set for about two months.', target: 'because', choices: ['because', 'because of'], focus: 'Because before a clause', thai: 'ฤดูร้อนมีแสงแดดเพราะดวงอาทิตย์ไม่ตกเป็นเวลาประมาณสองเดือน', why: 'The sun doesn’t set is a clause with a subject and verb. Because introduces that clause; because of requires a noun phrase.', whyThai: 'the sun doesn’t set เป็นประโยคย่อยที่มีประธานและกริยา ใช้ because นำหน้าได้ ส่วน because of ต้องตามด้วยกลุ่มคำนาม' },
  // Retired the cloudy/rainy and-or item: both options fit the displayed English.
  { sentence: 'Life can be hard here, but we love our home.', target: 'but', choices: ['but', 'despite'], focus: 'But joining contrasting clauses', thai: 'ชีวิตที่นี่อาจยากลำบาก แต่พวกเรารักบ้านของเรา', why: 'But joins two complete clauses. Despite cannot directly introduce the clause we love our home; it requires a noun phrase or an -ing form.', whyThai: 'but เชื่อมประโยคย่อยสองประโยค ส่วน despite ต้องตามด้วยกลุ่มคำนามหรือรูป ing จึงใช้นำหน้า we love our home โดยตรงไม่ได้' },
]
