// Short practice sentences adapted from the supplied readings, not quotations.
// Keep the original story excerpt separately for source attribution.
export const vocabularyContexts: Readonly<Record<string, string>> = {
  airport: 'I hugged her at the airport.',
  apartments: 'Many people live in apartments.',
  basketball: 'I play basketball with my friends.',
  beach: 'The treehouses are near the beach.',
  bird: 'A birder never hurts a bird.',
  birdwatching: 'Birdwatching is a fun hobby.',
  bread: 'Shawarma is served with pita bread.',
  brother: 'I have a brother and a sister.',
  buses: 'The buses stop in traffic.',
  cars: 'The cars stop in traffic.',
  cats: 'These are not pet cats.',
  cave: 'People live in cave houses.',
  cheese: 'The sauce has crumbled cheese.',
  child: 'Your child will write a lot.',
  cities: 'Many people live in cities.',
  city: 'Many people live in the city.',
  cold: 'It is cold outside.',
  corn: 'The corn is cooked over hot coals.',
  countryside: 'There are farms in the countryside.',
  diary: 'Birders write in a diary.',
  doctor: 'My mother is a doctor.',
  elevator: 'Riders take an elevator to the platform.',
  family: 'We are a big family.',
  farms: 'There are farms in the countryside.',
  father: 'My father is a police officer.',
  fish: 'Fish and chips is popular.',
  fishing: 'Fishing is a job on this island.',
  folders: 'Your child needs four folders.',
  food: 'I save food for the cats.',
  friends: 'I play basketball with my friends.',
  gate: 'I ran to the gate.',
  grandfather: 'My grandfather is a pilot.',
  grandmother: 'My grandmother is a chef.',
  handouts: 'Folders keep your handouts together.',
  hills: 'Birders hike up and down hills.',
  hobby: 'Birdwatching is a fun hobby.',
  houses: 'There are houses in the suburbs.',
  island: 'Roger lives on an island.',
  meat: 'Shawarma is made with spiced meat.',
  midnight: 'It is midnight in Chicago.',
  morning: 'It is early morning in Rome.',
  mother: 'My mother is a doctor.',
  nest: 'A bird builds its nest.',
  notebooks: 'Please get five notebooks for school.',
  ocean: 'The island is in the Atlantic Ocean.',
  pancakes: 'My sister made pancakes for breakfast.',
  pencils: 'Please get a pen and pencils.',
  people: 'There are eight people in my family.',
  photographs: 'People take photographs of the house.',
  pilot: 'My grandfather is a pilot.',
  plane: 'My plane was ready to leave.',
  platform: 'Riders wait on the platform.',
  police: 'My father is a police officer.',
  questions: 'Please answer these questions about your child.',
  rocks: 'People made houses inside large rocks.',
  salt: 'Fish and chips is good with salt.',
  sauce: 'The corn is covered with sauce.',
  school: 'Your child needs supplies for school.',
  shape: 'Look at the bird’s size and shape.',
  sister: 'I went to visit my sister.',
  sky: 'Stars sweep across the dark sky.',
  stars: 'There are shooting stars tonight.',
  station: 'The train goes from station to station.',
  storms: 'We often have strong storms.',
  streets: 'Train tracks run above the streets.',
  suburbs: 'There are houses in the suburbs.',
  suitcase: 'I took my suitcase to the airport.',
  sun: 'The sun is already warm.',
  supplies: 'Your child needs school supplies.',
  sweaters: 'I wear warm wool sweaters.',
  teacher: 'Barbara Smith is a teacher.',
  temperature: 'The temperature will drop below freezing.',
  thunder: 'You think you hear thunder.',
  ticket: 'Riders buy a train ticket.',
  tracks: 'Steel columns support the train tracks.',
  traffic: 'Cars stop in traffic.',
  train: 'Riding the train is easy.',
  treehouses: 'You can stay in these treehouses.',
  trip: 'I had a wonderful trip.',
  vinegar: 'Fish and chips is good with vinegar.',
  volcano: 'Roger lives next to a volcano.',
  warm: 'The sun is already warm.',
  water: 'The house is over the water.',
  weather: 'The weather is quite dry here.',
  winter: 'We see northern lights in winter.',
  woods: 'Birders hike in the woods.',
}
