import { useMemo, useState } from 'react'
import { getQuizCatalogue } from '../learning/quizContent'
import { buildWordConfidence, type ConfidenceStatus } from '../learning/wordConfidence'
import type { ProgressEvent } from '../learning/progressData'

const statuses: ConfidenceStatus[] = ['Confident', 'Building confidence', 'Needs review', 'Not practised']
const colours: Record<ConfidenceStatus, string> = { Confident: 'bg-emerald-100 text-emerald-900', 'Building confidence': 'bg-blue-50 text-blue-900', 'Needs review': 'bg-amber-100 text-amber-900', 'Not practised': 'bg-slate-100 text-slate-600' }
export default function WordConfidencePanel({ events, now }: { events: readonly ProgressEvent[]; now: number }) {
  const [filter, setFilter] = useState<string>('All')
  const [search, setSearch] = useState('')
  const [mode, setMode] = useState('all')
  const [page, setPage] = useState(0)
  const rows = useMemo(() => { const bank = getQuizCatalogue(); return buildWordConfidence(events, [...bank.vocabulary, ...bank.sentences], now) }, [events, now])
  const filtered = rows.filter(r => (filter === 'All' || r.status === filter) && (mode === 'all' || r.mode === mode) && r.word.includes(search.trim().toLowerCase()))
  return <section aria-label="Word confidence" className="space-y-5">
    <div><h2 className="text-2xl font-bold">Word confidence</h2><p className="mt-2 text-sm text-slate-500">Which words are sticking, and which need another go.</p></div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{statuses.map(status => <button key={status} type="button" aria-pressed={filter === status} onClick={() => { setFilter(filter === status ? 'All' : status); setPage(0) }} className={`rounded-xl border p-4 text-left ${colours[status]} ${filter === status ? 'ring-2 ring-teal-700' : ''}`}><strong className="block text-3xl">{rows.filter(r => r.status === status).length}</strong><span className="text-sm">{status}</span></button>)}</div>
    <details className="text-sm leading-6 text-slate-600"><summary className="cursor-pointer font-semibold">How confidence is measured</summary><p className="mt-2">Confident means at least five correct answers without word help, across three rounds and three Bangkok dates since the last mistake or helped answer. Particles also require three different sentence prompts. A week without practice moves a word to Needs review. This describes performance on these exercises, not a complete assessment of language ability.</p><p>Old imported totals and answers without round details cannot establish confidence. Only the word being tested receives credit.</p></details>
    <div className="flex flex-wrap gap-3"><input aria-label="Search confidence words" placeholder="Find a word…" value={search} onChange={e => { setSearch(e.target.value); setPage(0) }} className="min-w-0 rounded-lg border px-3 py-2" /><select aria-label="Confidence status" value={filter} onChange={e => { setFilter(e.target.value); setPage(0) }} className="rounded-lg border px-3 py-2"><option>All</option>{statuses.map(s => <option key={s}>{s}</option>)}</select><select aria-label="Practice type" value={mode} onChange={e => { setMode(e.target.value); setPage(0) }} className="rounded-lg border px-3 py-2"><option value="all">Both modes</option><option value="vocabulary">Vocabulary</option><option value="sentences">Particles</option></select></div>
    <p role="status" className="text-xs text-slate-500">{filtered.length} words · {filtered.length ? page * 25 + 1 : 0}–{Math.min((page + 1) * 25, filtered.length)}</p>
    <div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{['Word', 'Mode', 'Confidence', 'Correct / attempts', 'Independent evidence', 'Last practised'].map(h => <th key={h} className="whitespace-nowrap p-3">{h}</th>)}</tr></thead><tbody>{filtered.slice(page * 25, (page + 1) * 25).map(r => <tr key={r.key} className="border-t"><th scope="row" className="p-3">{r.word}</th><td className="p-3">{r.mode === 'sentences' ? 'Particles' : 'Vocabulary'}</td><td className="p-3"><span className={`whitespace-nowrap rounded-full px-3 py-1 text-xs ${colours[r.status]}`}>{r.status}</span></td><td className="p-3">{r.correct} / {r.correct + r.wrong}{r.helped > 0 && <span className="block text-xs text-slate-500">{r.helped} with help</span>}{r.legacy > 0 && <span className="block text-xs text-slate-500">{r.legacy} older attempts</span>}</td><td className="p-3 text-xs leading-5">{r.successful} correct · {r.days} days · {r.rounds} rounds{r.mode === 'sentences' && <span className="block">{r.examples} sentence variants</span>}</td><td className="whitespace-nowrap p-3 text-xs">{r.lastAnswered ? new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Bangkok', dateStyle: 'medium' }).format(new Date(r.lastAnswered)) : 'Not recorded'}</td></tr>)}</tbody></table></div>
    {!filtered.length && <p className="text-sm text-slate-500">No words match this view.</p>}
    {filtered.length > 25 && <div className="flex justify-between"><button disabled={!page} onClick={() => setPage(p => p - 1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Previous</button><button disabled={(page + 1) * 25 >= filtered.length} onClick={() => setPage(p => p + 1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Next</button></div>}
  </section>
}
