export type CourseUnit = {
  unit: number
  title: string
  pages: string
  vocabulary: readonly string[]
  grammar: readonly string[]
  listening: string
  speaking: string
  reading: string
  writing: string
  pronunciation: string
  project: string
}

export const courseScope: readonly CourseUnit[] = [
  {
    unit: 1,
    title: "We're a Family",
    pages: 'Page 6',
    vocabulary: ['Family', 'Extended family', 'Jobs & personal information', 'Basic descriptions'],
    grammar: ['Present be verbs', 'Interrogative be verbs'],
    listening: 'Identify family members',
    speaking: 'Ask and answer personal questions',
    reading: "Read about family members’ jobs",
    writing: 'Write about family members',
    pronunciation: 'Introduction to vowel sounds (1)',
    project: 'Make a family tree',
  },
  {
    unit: 2,
    title: 'Back to School',
    pages: 'Page 18 · Review 1–2, page 30',
    vocabulary: ['School supplies', 'People at school', 'School equipment', 'School subjects'],
    grammar: ['The use of articles', 'Present be verbs (Wh-questions)'],
    listening: 'Understand who the people at school are',
    speaking: 'Talk about things in your classroom',
    reading: 'Read about the things you need for school',
    writing: 'Write about what you need for class',
    pronunciation: 'Introduction to vowel sounds (2)',
    project: 'Create a notice for a club',
  },
  {
    unit: 3,
    title: 'My House, My Home',
    pages: 'Page 32',
    vocabulary: ['Rooms in a home', 'Furniture', 'Living spaces', 'Parts of a house'],
    grammar: ['Demonstrative adjectives', 'Prepositions of place'],
    listening: 'Listen to people talk about things in a house',
    speaking: 'Talk about what is in a house',
    reading: 'Read about homes around the world',
    writing: "Write a description of what’s in your house",
    pronunciation: '/ʃ/ vs. /tʃ/',
    project: 'Design the perfect house',
  },
  {
    unit: 4,
    title: 'What Time Is It?',
    pages: 'Page 44 · Review 3–4, page 56',
    vocabulary: ['Modes of transportation', 'Routine activities', 'Time of the day, week, month, and year'],
    grammar: ['Prepositions of time (at, in, on, before, after)', 'Prepositions of place (at, in, on, above, beside)'],
    listening: 'Listen to a schedule',
    speaking: 'Talk about your routine',
    reading: 'Read about modes of transportation',
    writing: 'Write a schedule',
    pronunciation: '/ə/',
    project: "Compare people’s routines",
  },
  {
    unit: 5,
    title: 'Time to Play!',
    pages: 'Page 58',
    vocabulary: ['Hobbies', 'Instruments', 'Sports', 'Games'],
    grammar: ['Stative verbs', 'Adverbs of frequency'],
    listening: 'Listen to people talk about their free-time activities',
    speaking: 'Talk about hobbies',
    reading: 'Read about hobbies',
    writing: 'Write an email',
    pronunciation: '/θ/ vs. /ð/',
    project: 'Make a guide',
  },
  {
    unit: 6,
    title: 'Looking Good!',
    pages: 'Page 70 · Review 5–6, page 82',
    vocabulary: ['Appearance', 'Clothing', 'Seasonal clothing', 'The weather'],
    grammar: ['Simple present (has / have)', 'Present continuous'],
    listening: 'Listen to a description of someone',
    speaking: 'Ask and answer questions about appearance',
    reading: 'Read about clothing around the world',
    writing: 'Describe your appearance in a message',
    pronunciation: '/ɪ/ vs. /i/',
    project: 'Find a person based on their physical description',
  },
  {
    unit: 7,
    title: "What’s for Lunch?",
    pages: 'Page 84',
    vocabulary: ['Kinds of foods', 'Ingredients', 'Quantifiers for food', 'Expressions for ordering'],
    grammar: ['Countable and uncountable nouns', 'Quantifiers (much, many, a lot, a little, a few)'],
    listening: 'Listen to likes and dislikes',
    speaking: 'Order food in a restaurant',
    reading: 'Read about street food',
    writing: 'Write about the food you eat',
    pronunciation: 'Plural sounds /s/, /z/, & /ɪz/',
    project: 'Write a food diary',
  },
  {
    unit: 8,
    title: 'Busy on the Weekend',
    pages: 'Page 96 · Review 7–8, page 108',
    vocabulary: ['Indoor chores', 'Outdoor chores'],
    grammar: ["can / can’t – ability, possibility, permission", 'Simple present – habit, unchanging situation, general truth, to give directions, to express fixed arrangements'],
    listening: 'Listen to people talk about chores',
    speaking: 'Talk about outdoor chores',
    reading: 'Read about different cultures',
    writing: 'Write about weekend plans',
    pronunciation: '/ər/',
    project: 'Create a weekly schedule',
  },
  {
    unit: 9,
    title: 'What Did You Do?',
    pages: 'Page 110',
    vocabulary: ['Places around town', 'Errands', 'Arrangements', 'Emotions'],
    grammar: ['Past be verbs (was / were)', 'Simple past tense'],
    listening: 'Listen to past events',
    speaking: 'Talk about experiences',
    reading: 'Read about a trip',
    writing: 'Write about experiences',
    pronunciation: '/dʒ/ vs. /g/',
    project: 'Work with a group to write a story',
  },
  {
    unit: 10,
    title: "Sun’s Out!",
    pages: 'Page 122 · Review 9–10, page 134',
    vocabulary: ['Weather conditions', 'Weather forecasts', 'Seasonal activities'],
    grammar: ['Future will', 'Time clauses'],
    listening: 'Listen to a weather forecast',
    speaking: 'Talk about seasonal activities',
    reading: 'Read about weather',
    writing: 'Write plans based on the weather',
    pronunciation: '/n/ vs. /ŋ/',
    project: 'Give a weather forecast',
  },
]
