// Transcribed from the learner's textbook photographs; slash alternatives share an entry.
// Page 36 is printed in photo 10. Other page numbers follow the supplied exam outline.
export type ExamVocabulary = {
  word: string; thai: string; page: number; chapter: number; context: string
  plural?: string; alternative?: string; usage: 'count' | 'plural' | 'place' | 'time' | 'action' | 'mass'
}
const rows: [string, string, number, string, ExamVocabulary['usage'], string?, string?][] = [
 ['bathroom','ห้องน้ำ',34,'The bathroom has a shower.','count','bathrooms'],
 ['bedroom','ห้องนอน',34,'My bedroom has a bed.','count','bedrooms'],
 ['dining room','ห้องรับประทานอาหาร',34,'We eat in the dining room.','count','dining rooms'],
 ['kitchen','ห้องครัว',34,'The stove is in the kitchen.','count','kitchens'],
 ['living room','ห้องนั่งเล่น',34,'The couch is in the living room.','count','living rooms'],
 ['bathtub','อ่างอาบน้ำ',34,'The bathtub is in the bathroom.','count','bathtubs'],
 ['dresser','ตู้ลิ้นชักเก็บเสื้อผ้า',34,'My clothes are in the dresser.','count','dressers'],
 ['table','โต๊ะ',34,'The dishes are on the table.','count','tables'],
 ['refrigerator','ตู้เย็น',34,'The milk is in the refrigerator.','count','refrigerators'],
 ['couch','โซฟา',34,'We sit on the couch.','count','couches'],
 ['armchair','เก้าอี้นวมมีที่วางแขน',36,'My father sits in the armchair.','count','armchairs'],
 ['bed','เตียง',36,'The bed is beside the desk.','count','beds'],
 ['closet','ตู้หรือช่องเก็บเสื้อผ้า',36,'My clothes are in the closet.','count','closets'],
 ['clothes','เสื้อผ้า',36,'My clothes are clean.','plural'],
 ['lamp','โคมไฟ',36,'The lamp is on the table.','count','lamps'],
 ['mirror','กระจกเงา',36,'I look in the mirror.','count','mirrors'],
 ['shower','ฝักบัวอาบน้ำ',36,'There is a shower in the bathroom.','count','showers'],
 ['sink','อ่างล้างมือหรืออ่างล้างจาน',36,'The sink is in the kitchen.','count','sinks'],
 ['stove','เตาประกอบอาหาร',36,'We cook on the stove.','count','stoves'],
 ['toilet','โถส้วม',36,'There is a toilet in the bathroom.','count','toilets'],
 ['apartment','ห้องชุดพักอาศัย',38,'We live in an apartment.','count','apartments'],
 ['river','แม่น้ำ',38,'The river flows past the house.','count','rivers'],
 ['farm','ฟาร์ม',38,'There are cows on the farm.','count','farms'],
 ['cave','ถ้ำ',38,'The cave is inside the rock.','count','caves'],
 ['inside','ข้างใน',38,'The cat is inside the house.','place'],
 ['outside','ข้างนอก',38,'The dog is outside the house.','place'],
 ['countryside','ชนบท',38,'We live in the countryside.','place'],
 ['city','เมือง',38,'Many people live in the city.','count','cities'],
 ['door','ประตู',40,'Please open the door.','count','doors'],
 ['garden','สวน',40,'There are flowers in the garden.','count','gardens'],
 ['roof','หลังคา',40,'The roof keeps the rain out.','count','roofs'],
 ['stairs','บันได',40,'We climb the stairs.','plural'],
 ['window','หน้าต่าง',40,'I look out of the window.','count','windows'],
 ['television','โทรทัศน์',40,'There is a television in the bedroom.','count','televisions'],
 ['yard','บริเวณรอบบ้าน',40,'The children play in the yard.','count','yards'],
 ['wall','ผนัง',40,'The map is on the wall.','count','walls'],
 ['morning','ตอนเช้า',46,'I wake up in the morning.','time'],
 ['afternoon','ตอนบ่าย',46,'We play in the afternoon.','time'],
 ['today','วันนี้',46,'We have practice today.','time'],
 ['tomorrow','พรุ่งนี้',46,'We go to school tomorrow.','time'],
 ['evening','ตอนเย็น',46,'We eat in the evening.','time'],
 ['night','กลางคืน',46,'I sleep at night.','time'],
 ['practice','การฝึกซ้อม',46,'Football practice starts at four.','mass'],
 ['weekend','วันหยุดสุดสัปดาห์',46,'We play on the weekend.','time'],
 ['wake up','ตื่นนอน',48,'I wake up at six.','action'],
 ['go to bed','เข้านอน',48,'I go to bed at nine.','action',undefined,'go to sleep'],
 ['get dressed','แต่งตัว',48,'I get dressed after my shower.','action'],
 ['brush my teeth','แปรงฟันของฉัน',48,'I brush my teeth every morning.','action'],
 ['make my bed','จัดเตียงของฉัน',48,'I make my bed every morning.','action'],
 ['pack my bag','จัดกระเป๋าของฉัน',48,'I pack my bag before school.','action'],
 ['go to practice','ไปฝึกซ้อม',48,'I go to practice after school.','action'],
 ['do my homework','ทำการบ้านของฉัน',48,'I do my homework after school.','action'],
 ['play a game','เล่นเกม',48,'We play a game after dinner.','action'],
 ['clean my room','ทำความสะอาดห้องของฉัน',48,'I clean my room on the weekend.','action'],
 ['plane','เครื่องบิน',50,'The plane flies above the city.','count','planes'],
 ['taxi','รถแท็กซี่',50,'We take a taxi to the station.','count','taxis'],
 ['car','รถยนต์',50,'The car stops at the gate.','count','cars'],
 ['subway','รถไฟใต้ดิน',50,'We take the subway to school.','count','subways'],
 ['bus','รถโดยสาร',50,'The bus stops near my house.','count','buses'],
 ['bicycle','จักรยาน',50,'I ride my bicycle to school.','count','bicycles','bike'],
 ['train','รถไฟ',50,'The train moves from station to station.','count','trains'],
 ['fly','บิน',50,'Birds fly above the trees.','action'],
 ['drive','ขับรถ',50,'I can drive a car.','action'],
 ['ride','ขี่หรือนั่งพาหนะ',50,'I ride my bike to school.','action'],
]
export const finalExamVocabulary: readonly ExamVocabulary[] = rows.map(([word,thai,page,context,usage,plural,alternative]) => ({word,thai,page,chapter:page<44?3:4,context,usage,plural,alternative}))
